name: Build and Publish image

# Event that trigger workflow
on:
  [workflow_dispatch]
  # to run a workflow manually, configure your workflow to run on workflow_dispatch in the default branch

jobs: 
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build image
      run: docker build ./dockerdir/ -t zhaohuiwang/make-poetry-git:latest
    - name: push image to docker hub
      run: |
        docker login -u zhaohuiw -p ${{ secrets.DH_PAT }} 
        docker push zhaohuiwang/make-poetry-git:latest
      # login Dockerhub

# There is template at Github: Login GitHub > Repositories > select the name > Actions > Dcker image > docker-image.yml template
# The default file location: <repository-name>/.github/workflows/docker-image.yml

# we can also set the event that trigger workflow on specified push (not all pushes)
#on:
#  push:
#    branches: -main
#    paths:
#      - 'path-to-Dockerfile/Dockerfile'
#      - 'path-to-Dockerfile/Dockerfile'
#      # e.g. front end and back end Dockerfile
# https://www.youtube.com/watch?v=x7f9x30W_dI
# https://github.com/rishabkumar7/aws-devops-capstone-project
# https://github.com/docker/build-push-action


